let users = [
    {
        id:0,
        name:'myZOO',
        comments:'',
        login_information:{
            login_name:'myZOO',
            login_pass:'adc1234@',
            login_email:'zoocp123@gmail.com',
        },
        avatar_url:'',
    },
    {
        id:0,
        name:'Linh',
        comments:'',
        login_information:{
            login_name:'Linh',
            login_pass:'adc1234@',
            login_email:'linhcp123@gmail.com',
        },
        avatar_url:'',
    }, 
    {
        id:0,
        name:'Duy',
        comments:'',
        login_information:{
            login_name:'Duy',
            login_pass:'adc1234@',
            login_email:'duyvucp123@gmail.com',
        },
        avatar_url:'',
    },
    {
        id:3,
        name:'javan',
        comments:'',
        login_information:{
            login_name:'javan',
            login_pass:'adc1234@',
            login_email:'javanp123@gmail.com',
        },
        avatar_url:'',
    },
    {
        id:4,
        name:'lord_of_the_star',
        comments:'',
        login_information:{
            login_name:'lord_of_the_star',
            login_pass:'adc1234@',
            login_email:'lordofthestarcp123@gmail.com',
        },
        avatar_url:'',
    }
];
export default users